baseURL = "https://www.stunkymonkey.de/"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true


[permalinks]
	posts = "/posts/:year/:month/:title/"

[params]
	dateform        = "2. Jan 2006"
	dateformShort   = "2. Jan"
	dateformNum     = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04 -0700"

	# Metadata
	description = "Homepage and blog of Felix B端hler"
	keywords = "homepage, blog, computer, science, informatics, development, programming"
	avatarURL = "/profile-picture.jpg"

	homeSubtitle = "I'm stunkymonkey. A guy from Stuttgart, Germany. At my free time I love to code."
	colorScheme = "auto"

	[params.logo]
		logoText     = "Felix B端hler"
		logoHomeLink = "/"

	# Social icons
	[[params.social]]
		name = "Github"
		icon = "fa fa-github"
		weight = 1
		url = "https://github.com/Stunkymonkey"
	[[params.social]]
		name = "Gitlab"
		icon = "fa fa-gitlab"
		weight = 2
		url = "https://gitlab.com/Stunkymonkey"
	[[params.social]]
		name = "LinkedIn"
		icon = "fa fa-linkedin"
		weight = 2
		url = "https://www.linkedin.com/in/felix-b%C3%BChler-5a27131a0/"
	[[params.social]]
		name = "Email"
		icon = "fa fa-envelope"
		url = "mailto:website@stunkymonkey.de"
		weight = 5

	[languages]
		[languages.en]
			title = "Felix B端hler"
			copyright = "Felix B端hler"
		[languages.en.params]
				keywords = ""
				subtitle = "I'm stunkymonkey. A guy from Stuttgart, Germany. At my free time I love to code."
				readOtherPosts = "Read other posts"
	[menu]
		[[menu.main]]
			identifier = "about"
			name       = "About"
			url        = "/about"
#		[[menu.main]]
#			identifier = "cv"
#			name       = "CV"
#			url        = "/cv"
		[[menu.main]]
			identifier = "blog"
			name       = "Blog"
			url        = "/blog"
		[[menu.main]]
			identifier = "projects"
			name       = "Projects"
			url        = "/projects"
